### ISSUE TITLE
ripples don't collide?

### ISSUE THREAD

**Issue by evnix** [victorqribeiro/rippleEffect#1]
https://victorribeiro.com/rippleEffect/

when i create two ripples side by side, they don't collide and act as expected as normal ripples.

**Comment by victorqribeiro** [comment]
"Notes: This method is by no means a highly accurate simulation of rippling water (though it is not too far off). Ripples can pass through each other quite happily, and will reflect off the walls. One thing you may notice, however, is that the ripples are not quite circular."

words from the author

**Comment by evnix** [comment]
> Ripples can pass through each other quite happily, and will reflect off the walls

This was news to me! But now I know better!
I guess we can officially close this first issue now :)
